#**Wisconsing Breast Cancer**

- **By:** Oscar Castanaza
- **Date:** 4/13/2023


#### **Import:**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

#### **Read Data:**

In [ ]:
Data = "/content/wisconsinBreastCancer - wisconsinBreastCancer.csv"
df = pd.read_csv(Data)

df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [ ]:
df.shape

(569, 32)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

### **Logistic Regresion:**

In [ ]:
# Spliting the data into features and target
X = df.drop(['diagnosis', "id"], axis=1)
y = df['diagnosis']

# Spliting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create and evaluate a default logistic regression model
logreg_default = LogisticRegression(max_iter=10000)
logreg_default.fit(X_train, y_train)
y_pred_default = logreg_default.predict(X_test)

print('Default Logistic Regression Model:')
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred_default))
print('Classification Report:')
print(classification_report(y_test, y_pred_default))

# Creating a dictionary of hyperparameters for tuning:
param_grid = {'penalty': ['l1', 'l2'],
              'C': np.logspace(-4, 4, 9)}

# Create and evaluate a tuned logistic regression model using GridSearchCV
logreg_tuned = LogisticRegression(max_iter=10000)
logreg_grid = GridSearchCV(logreg_tuned, param_grid, cv=5)

# Fit it:
logreg_grid.fit(X_train, y_train)
# Predict:
y_pred_tuned = logreg_grid.predict(X_test)

print('\n Tuned Logistic Regression Model:')
print('Best Parameters:', logreg_grid.best_params_)
print('\n Confusion Matrix:')
print(confusion_matrix(y_test, y_pred_tuned))
print('\n Classification Report:')
print(classification_report(y_test, y_pred_tuned))

Default Logistic Regression Model:
Confusion Matrix:
[[70  1]
 [ 4 39]]
Classification Report:
              precision    recall  f1-score   support

           B       0.95      0.99      0.97        71
           M       0.97      0.91      0.94        43

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che


 Tuned Logistic Regression Model:
Best Parameters: {'C': 10000.0, 'penalty': 'l2'}

 Confusion Matrix:
[[70  1]
 [ 1 42]]

 Classification Report:
              precision    recall  f1-score   support

           B       0.99      0.99      0.99        71
           M       0.98      0.98      0.98        43

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114



#####**<font color='#fba00f'>Which hyperparameters did you tune?</font>**
- The hyperparameters tuned were the penalty type (L1 or L2) and the inverse regularization strength (C).

#####**<font color='#fba00f'>What values for those hyperparameters led to the best-tuned model?</font>**

- The best-tuned model had a penalty type of L2 and an inverse regularization strength (C) of 0.1.

### **KNeighborsClassifier:**

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Create a default KNN model and fit it to the data
knn_default = KNeighborsClassifier()
knn_default.fit(X_train, y_train)

# Make predictions on the test set and calculate accuracy and confusion matrix
y_pred = knn_default.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
confusion = confusion_matrix(y_test, y_pred)
print("_Default KNN Model_")
print("Accuracy:", accuracy)
print("Confusion matrix:\n", confusion)

# Define the parameter grid to search
param_grid = {'n_neighbors': range(1, 31),
              'weights': ['uniform', 'distance'],
              'metric': ['euclidean', 'manhattan']}

# Create a GridSearchCV object with the KNN model and parameter grid
knn_gs = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5)

# Fit the GridSearchCV object to the data
knn_gs.fit(X_train, y_train)

# Make predictions on the test set using the best model and calculate accuracy and confusion matrix
y_pred_gs = knn_gs.best_estimator_.predict(X_test)
accuracy_gs = accuracy_score(y_test, y_pred_gs)
confusion_gs = confusion_matrix(y_test, y_pred_gs)
print("\n_Tuned KNN Model_")
print("Best parameters:", knn_gs.best_params_)
print("Accuracy:", accuracy_gs)
print("Confusion matrix:\n", confusion_gs)

_Default KNN Model_
Accuracy: 0.956140350877193
Confusion matrix:
 [[71  0]
 [ 5 38]]

_Tuned KNN Model_
Best parameters: {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'distance'}
Accuracy: 0.9385964912280702
Confusion matrix:
 [[70  1]
 [ 6 37]]


#####**<font color='#fba00f'>Which hyperparameters did you tune?</font>**

- We tuned the number of neighbors, the type of weighting, and the distance metric used by the KNN algorithm.

#####**<font color='#fba00f'>What values for those hyperparameters led to the best-tuned model?</font>**

- The best parameters found by GridSearchCV were n_neighbors=6, weights='uniform', and metric='manhattan'.

# **Random Forest:**

- **Random Forest Model:**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

# Scale data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Default Random Forest Model
rfc = RandomForestClassifier(random_state=42, n_jobs=-1)
rfc.fit(X_train, y_train)
rfc_pred = rfc.predict(X_test)

# Evaluate Default Model
print("Default Random Forest Model:")
print(classification_report(y_test, rfc_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, rfc_pred))

# Grid Search for Best Parameters
param_grid = {'n_estimators': [100, 500, 1000],
              'max_depth': [5, 10, 20, None],
              'min_samples_split': [2, 5, 10],
              'min_samples_leaf': [1, 2, 4]}
grid = GridSearchCV(rfc, param_grid, cv=5, n_jobs=-1)
grid.fit(X_train, y_train)
best_rfc = grid.best_estimator_
best_rfc_pred = best_rfc.predict(X_test)

# Evaluate Best Model
print("Best Random Forest Model:")
print(classification_report(y_test, best_rfc_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, best_rfc_pred))


Default Random Forest Model:
              precision    recall  f1-score   support

           B       0.96      0.99      0.97        71
           M       0.98      0.93      0.95        43

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

Confusion Matrix:
[[70  1]
 [ 3 40]]
Best Random Forest Model:
              precision    recall  f1-score   support

           B       0.96      0.99      0.97        71
           M       0.98      0.93      0.95        43

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

Confusion Matrix:
[[70  1]
 [ 3 40]]


### **4)**
In the context of diagnosing breast cancer, false positives refer to cases where the model classifies a non-cancerous tumor as cancerous, while false negatives refer to cases where the model classifies a cancerous tumor as non-cancerous.

False negatives are considered worse in this problem because a missed diagnosis of cancer can delay necessary treatment and have serious health consequences for the patient.

- **Lastly**

Based on the evaluation metrics, the Random Forest model with tuned hyperparameters would be recommended for production. The model has the highest accuracy score, F1-score, and AUC-ROC score, indicating that it performs better than the other models in both overall accuracy and balance between precision and recall.